# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-30 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MullevelAPP.Customer')),
                ('ename', models.CharField(max_length=20)),
                ('sal', models.IntegerField()),
            ],
            bases=('MullevelAPP.customer',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('emp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MullevelAPP.Emp')),
                ('sname', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
            ],
            bases=('MullevelAPP.emp',),
        ),
    ]
